# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/asaf/Desktop/projects/computer-construct-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/asaf/Desktop/projects/computer-construct-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asaf/Desktop/projects/computer-construct-2/CMakeFiles /home/asaf/Desktop/projects/computer-construct-2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asaf/Desktop/projects/computer-construct-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CacheSim

# Build rule for target.
CacheSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CacheSim
.PHONY : CacheSim

# fast build rule for target.
CacheSim/fast:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/build
.PHONY : CacheSim/fast

Cache.o: Cache.cpp.o

.PHONY : Cache.o

# target to build an object file
Cache.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Cache.cpp.o
.PHONY : Cache.cpp.o

Cache.i: Cache.cpp.i

.PHONY : Cache.i

# target to preprocess a source file
Cache.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Cache.cpp.i
.PHONY : Cache.cpp.i

Cache.s: Cache.cpp.s

.PHONY : Cache.s

# target to generate assembly for a file
Cache.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Cache.cpp.s
.PHONY : Cache.cpp.s

CacheSimulator.o: CacheSimulator.cpp.o

.PHONY : CacheSimulator.o

# target to build an object file
CacheSimulator.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/CacheSimulator.cpp.o
.PHONY : CacheSimulator.cpp.o

CacheSimulator.i: CacheSimulator.cpp.i

.PHONY : CacheSimulator.i

# target to preprocess a source file
CacheSimulator.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/CacheSimulator.cpp.i
.PHONY : CacheSimulator.cpp.i

CacheSimulator.s: CacheSimulator.cpp.s

.PHONY : CacheSimulator.s

# target to generate assembly for a file
CacheSimulator.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/CacheSimulator.cpp.s
.PHONY : CacheSimulator.cpp.s

DataBlock.o: DataBlock.cpp.o

.PHONY : DataBlock.o

# target to build an object file
DataBlock.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/DataBlock.cpp.o
.PHONY : DataBlock.cpp.o

DataBlock.i: DataBlock.cpp.i

.PHONY : DataBlock.i

# target to preprocess a source file
DataBlock.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/DataBlock.cpp.i
.PHONY : DataBlock.cpp.i

DataBlock.s: DataBlock.cpp.s

.PHONY : DataBlock.s

# target to generate assembly for a file
DataBlock.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/DataBlock.cpp.s
.PHONY : DataBlock.cpp.s

Entry.o: Entry.cpp.o

.PHONY : Entry.o

# target to build an object file
Entry.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Entry.cpp.o
.PHONY : Entry.cpp.o

Entry.i: Entry.cpp.i

.PHONY : Entry.i

# target to preprocess a source file
Entry.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Entry.cpp.i
.PHONY : Entry.cpp.i

Entry.s: Entry.cpp.s

.PHONY : Entry.s

# target to generate assembly for a file
Entry.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Entry.cpp.s
.PHONY : Entry.cpp.s

VictimCache.o: VictimCache.cpp.o

.PHONY : VictimCache.o

# target to build an object file
VictimCache.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/VictimCache.cpp.o
.PHONY : VictimCache.cpp.o

VictimCache.i: VictimCache.cpp.i

.PHONY : VictimCache.i

# target to preprocess a source file
VictimCache.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/VictimCache.cpp.i
.PHONY : VictimCache.cpp.i

VictimCache.s: VictimCache.cpp.s

.PHONY : VictimCache.s

# target to generate assembly for a file
VictimCache.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/VictimCache.cpp.s
.PHONY : VictimCache.cpp.s

Way.o: Way.cpp.o

.PHONY : Way.o

# target to build an object file
Way.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Way.cpp.o
.PHONY : Way.cpp.o

Way.i: Way.cpp.i

.PHONY : Way.i

# target to preprocess a source file
Way.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Way.cpp.i
.PHONY : Way.cpp.i

Way.s: Way.cpp.s

.PHONY : Way.s

# target to generate assembly for a file
Way.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/Way.cpp.s
.PHONY : Way.cpp.s

cacheSim.o: cacheSim.cpp.o

.PHONY : cacheSim.o

# target to build an object file
cacheSim.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/cacheSim.cpp.o
.PHONY : cacheSim.cpp.o

cacheSim.i: cacheSim.cpp.i

.PHONY : cacheSim.i

# target to preprocess a source file
cacheSim.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/cacheSim.cpp.i
.PHONY : cacheSim.cpp.i

cacheSim.s: cacheSim.cpp.s

.PHONY : cacheSim.s

# target to generate assembly for a file
cacheSim.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/cacheSim.cpp.s
.PHONY : cacheSim.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CacheSim.dir/build.make CMakeFiles/CacheSim.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... CacheSim"
	@echo "... edit_cache"
	@echo "... Cache.o"
	@echo "... Cache.i"
	@echo "... Cache.s"
	@echo "... CacheSimulator.o"
	@echo "... CacheSimulator.i"
	@echo "... CacheSimulator.s"
	@echo "... DataBlock.o"
	@echo "... DataBlock.i"
	@echo "... DataBlock.s"
	@echo "... Entry.o"
	@echo "... Entry.i"
	@echo "... Entry.s"
	@echo "... VictimCache.o"
	@echo "... VictimCache.i"
	@echo "... VictimCache.s"
	@echo "... Way.o"
	@echo "... Way.i"
	@echo "... Way.s"
	@echo "... cacheSim.o"
	@echo "... cacheSim.i"
	@echo "... cacheSim.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

